- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - npm
    - nodejs-legacy
  become: true

- name: Create /src directory
  file:
    path: /src
    state: directory
    mode: 0666
  become: true

- name: Clone repository
  git:
    repo: 'https://github.com/Skorfulose/parallel-piper.git'
    dest: /src/parallel-piper
    force: yes

- name: Install node dependencies
  npm:
    path: /src/parallel-piper
    state: latest

- name: Run webpack build
  command: build.sh
  args:
    chdir: /src/parallel-piper/
